[tool.poetry]
name = "repl_python3_coindcx"
version = "0.1.0"
description = ""
authors = ["paramphy <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.1"
mailjet-rest = "^1.3.4"
tqdm = "^4.62.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
